### ISSUE TITLE
GraalVM native image instead of the JVM

### ISSUE THREAD

**Issue by sdeleuze** [maxday/lambda-perf#3]
It would make more sense to compile the Java workload with GraalVM native image, cold start with JVM make no sense for this kind of use case.

I guess that's similar to #2 raised for .Net.

**Comment by alexanderankin** [comment]
I tried, its getting the better of me, going to include some pieces here in case i have an opportunity to come back to it.

<details><summary>the error i was seeing (from aws/aws-lambda-java-libs#205)</summary>

```diff
Exception in thread "main" java.lang.Error: com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil$ReflectException: java.lang.NoSuchFieldException: logger
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:195)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:188)
Caused by: com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil$ReflectException: java.lang.NoSuchFieldException: logger
	at com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil.setStaticField(ReflectUtil.java:660)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.setupRuntimeLogger(AWSLambda.java:153)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:204)
	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:193)
	... 1 more
Caused by: java.lang.NoSuchFieldException: logger
	at java.base@17.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil.setStaticField(ReflectUtil.java:654)
	... 4 more
```
</details>

<details><summary>the changes made for lamda-perf/s3-uploader/runtimes</summary>

```diff
diff --git a/s3-uploader/runtimes/java11/Dockerfile b/s3-uploader/runtimes/java11/Dockerfile
index 89a6a12..4443029 100644
--- a/s3-uploader/runtimes/java11/Dockerfile
+++ b/s3-uploader/runtimes/java11/Dockerfile
@@ -1,14 +1,19 @@
-FROM public.ecr.aws/lambda/java:11 as builder
+FROM debian:unstable-slim as builder
+RUN apt update && \
+    apt install curl zip unzip ca-certificates -y --no-install-suggests --no-install-recommends && \
+    curl -s "https://get.sdkman.io" | bash
+SHELL ["bash", "-lc"]
+RUN sdk install java 22.3.r17-grl && gu install native-image
 WORKDIR /tmpBuild
-RUN yum install -y unzip
 RUN  curl -k -L -v -X GET https\://services.gradle.org/distributions/gradle-7.5.1-bin.zip > gradle-7.5.1-bin.zip
 RUN unzip -d /opt/gradle gradle-7.5.1-bin.zip
+RUN apt install build-essential zlib1g-dev --no-install-suggests --no-install-recommends -y
 
 COPY src ./src
 COPY build.gradle .
 
-RUN JAVA_HOME=/var/lang /opt/gradle/gradle-7.5.1/bin/gradle :buildZip
+RUN /opt/gradle/gradle-7.5.1/bin/gradle nativeCompile
 
 FROM scratch
-COPY --from=builder /tmpBuild/build/distributions/code.zip /
+COPY --from=builder /tmpBuild/build/native/nativeCompile/tmpBuild /code.zip
 ENTRYPOINT ["/code.zip"]
\ No newline at end of file
diff --git a/s3-uploader/runtimes/java11/build.gradle b/s3-uploader/runtimes/java11/build.gradle
index dd34e66..5bfa914 100644
--- a/s3-uploader/runtimes/java11/build.gradle
+++ b/s3-uploader/runtimes/java11/build.gradle
@@ -1,4 +1,15 @@
-apply plugin: 'java'
+import org.graalvm.buildtools.gradle.tasks.BuildNativeImageTask
+
+plugins {
+    id 'java'
+    id 'application'
+    id 'org.graalvm.buildtools.native' version '0.9.19'
+    id 'com.github.johnrengelman.shadow' version '7.1.2'
+}
+
+application {
+    mainClass.set 'com.amazonaws.services.lambda.runtime.api.client.AWSLambda'
+}
 
 repositories {
     mavenCentral()
@@ -11,19 +22,39 @@ dependencies {
     implementation (
         'com.amazonaws:aws-lambda-java-core:1.2.1',
     )
+    implementation 'com.amazonaws:aws-lambda-java-runtime-interface-client:2.1.1'
+    implementation 'software.amazon.awssdk:sdk-core:2.19.26'
+    implementation 'org.graalvm.sdk:graal-sdk:22.3.1'
+    implementation 'org.slf4j:slf4j-api:1.7.28'
+    implementation 'org.slf4j:slf4j-simple:1.7.28'
+    implementation 'org.slf4j:jcl-over-slf4j:1.7.28'
 }
 
-task buildZip(type: Zip) {
-    baseName = "code"
-    from compileJava
-    from processResources
-    into('lib') {
-        from configurations.runtimeClasspath
+graalvmNative {
+    binaries {
+        main {
+            // https://www.graalvmonlambda.com/walkthrough/convert-to-graalvm/
+            buildArgs.add '--no-fallback'
+            buildArgs.add '--initialize-at-build-time=org.slf4j'
+            buildArgs.add '--enable-url-protocols=http,https'
+
+            buildArgs.add '-H:-AllowIncompleteClasspath'
+            buildArgs.add '-H:EnableURLProtocols=https'
+
+            // https://aws.amazon.com/blogs/developer/graalvm-native-image-support-in-the-aws-sdk-for-java-2-x/
+            buildArgs.add '-H:+ReportUnsupportedElementsAtRuntime'
+            buildArgs.add '-H:ReflectionConfigurationResources=META-INF/native-image/software.amazon.awssdk/sdk-core/reflect-config.json'
+            buildArgs.add '-H:ResourceConfigurationResources=META-INF/native-image/software.amazon.awssdk/sdk-core/resource-config.json'
+            buildArgs.add '-H:FallbackThreshold=0'
+            buildArgs.add '-H:ClassInitialization=org.slf4j:build_time'
+            // buildArgs.add '-H:Class=com.amazonaws.services.lambda.runtime.api.client.AWSLambda'
+            buildArgs.add '-H:Name=java11'
+        }
     }
 }
 
-build.dependsOn buildZip
-
-wrapper {
-    gradleVersion = '6.1'
+// https://graalvm.github.io/native-build-tools/0.9.19/gradle-plugin.html#long_classpath_and_fat_jar_support
+tasks.named('nativeCompile', BuildNativeImageTask) {
+    it.classpathJar = shadowJar.outputs.files.singleFile
+    it.dependsOn 'shadowJar'
 }

```

</details>

**Comment by sdeleuze** [comment]
Thanks for your feedback, I have not chcked but you may be able to fix the error you see by integrating the `[reflect-config.json](https://github.com/aws/aws-lambda-java-libs/pull/235/files)` files (potentially merging the 2 provided in a single one) in `META-INF/native-image` in your project.

**Comment by maxday** [comment]
Very good idea, I have a working example of a GraalVM native lambda function, I'll update the repo a bit later today!

**Comment by sdeleuze** [comment]
Thanks a lot for working on this, maybe worth keeping the regular JVM one in addition to the GraalVM one to compare the 2 flavors of Java.

**Comment by maxday** [comment]
Hi @sdeleuze, just want to give you an update on this.
Thanks to @mikrethor and #19, it will be live on tomorrow 9am EST at https://maxday.github.io/lambda-perf/

spoiler alert: 
<img width="709" alt="Screenshot 2023-02-13 at 3 34 15 PM" src="https://user-images.githubusercontent.com/864493/218568691-fdf2b7e6-cbd6-437a-be4e-bfd6c4461590.png">
